name: PickaxeEnchants
version: 1.0-SNAPSHOT
main: org.example.Main
api-version: 1.20
commands:
  rift:
    description: Opens the Dimensional Rift menu or manages rift progress.
    usage: /rift [set <dimension> <layer> [player]]
    aliases: [ rankup, dimension ]
  jackhammer:
  gemstonebox:
    description: Gives a gemstone box to the player
    usage: /gemstonebox
    permission: gemstonebox.use
  laser:
  tokens:
  pickaxe:
    description: Opens the pickaxe menu
    usage: /pickaxe openmenu
    permission: pickaxe.use
  adminpickaxe:
    description: Admin commands for pickaxe
    aliases: [ap]
    usage: /ap setlevel <enchantment> <level>
    permission: admin.pickaxe
permissions:
  pickaxe.use:
    description: Permission to use the pickaxe command
    default: true
  admin.pickaxe:
    description: Permission to use admin pickaxe commands
    default: op
  rift.admin.set:
    description: Allows setting a player's dimension and layer progress.
    default: op

